//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaasesoriaJAC.SocratesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/socratesWsSOAP.Dominio")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoalumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoalumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoalumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DnialumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrealumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidoalumno {
            get {
                return this.ApellidoalumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoalumnoField, value) != true)) {
                    this.ApellidoalumnoField = value;
                    this.RaisePropertyChanged("Apellidoalumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigoalumno {
            get {
                return this.CodigoalumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoalumnoField, value) != true)) {
                    this.CodigoalumnoField = value;
                    this.RaisePropertyChanged("Codigoalumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correoalumno {
            get {
                return this.CorreoalumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoalumnoField, value) != true)) {
                    this.CorreoalumnoField = value;
                    this.RaisePropertyChanged("Correoalumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dnialumno {
            get {
                return this.DnialumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.DnialumnoField, value) != true)) {
                    this.DnialumnoField = value;
                    this.RaisePropertyChanged("Dnialumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombrealumno {
            get {
                return this.NombrealumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrealumnoField, value) != true)) {
                    this.NombrealumnoField = value;
                    this.RaisePropertyChanged("Nombrealumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/socratesWsSOAP.Errores")]
    [System.SerializableAttribute()]
    public partial class ErroresException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Docente", Namespace="http://schemas.datacontract.org/2004/07/socratesWsSOAP.Dominio")]
    [System.SerializableAttribute()]
    public partial class Docente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidodocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigodocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreodocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DnidocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombredocenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidodocente {
            get {
                return this.ApellidodocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidodocenteField, value) != true)) {
                    this.ApellidodocenteField = value;
                    this.RaisePropertyChanged("Apellidodocente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigodocente {
            get {
                return this.CodigodocenteField;
            }
            set {
                if ((this.CodigodocenteField.Equals(value) != true)) {
                    this.CodigodocenteField = value;
                    this.RaisePropertyChanged("Codigodocente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correodocente {
            get {
                return this.CorreodocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreodocenteField, value) != true)) {
                    this.CorreodocenteField = value;
                    this.RaisePropertyChanged("Correodocente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dnidocente {
            get {
                return this.DnidocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.DnidocenteField, value) != true)) {
                    this.DnidocenteField = value;
                    this.RaisePropertyChanged("Dnidocente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombredocente {
            get {
                return this.NombredocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombredocenteField, value) != true)) {
                    this.NombredocenteField = value;
                    this.RaisePropertyChanged("Nombredocente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocratesWS.ISocratesService")]
    public interface ISocratesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/CrearAlumno", ReplyAction="http://tempuri.org/ISocratesService/CrearAlumnoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(sistemaasesoriaJAC.SocratesWS.ErroresException), Action="http://tempuri.org/ISocratesService/CrearAlumnoErroresExceptionFault", Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/socratesWsSOAP.Errores")]
        sistemaasesoriaJAC.SocratesWS.Alumno CrearAlumno(sistemaasesoriaJAC.SocratesWS.Alumno alumnoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/CrearAlumno", ReplyAction="http://tempuri.org/ISocratesService/CrearAlumnoResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno> CrearAlumnoAsync(sistemaasesoriaJAC.SocratesWS.Alumno alumnoCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ObtenerAlumno", ReplyAction="http://tempuri.org/ISocratesService/ObtenerAlumnoResponse")]
        sistemaasesoriaJAC.SocratesWS.Alumno ObtenerAlumno(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ObtenerAlumno", ReplyAction="http://tempuri.org/ISocratesService/ObtenerAlumnoResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno> ObtenerAlumnoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ModificarAlumno", ReplyAction="http://tempuri.org/ISocratesService/ModificarAlumnoResponse")]
        sistemaasesoriaJAC.SocratesWS.Alumno ModificarAlumno(sistemaasesoriaJAC.SocratesWS.Alumno alumnoModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ModificarAlumno", ReplyAction="http://tempuri.org/ISocratesService/ModificarAlumnoResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno> ModificarAlumnoAsync(sistemaasesoriaJAC.SocratesWS.Alumno alumnoModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/EliminarAlumno", ReplyAction="http://tempuri.org/ISocratesService/EliminarAlumnoResponse")]
        void EliminarAlumno(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/EliminarAlumno", ReplyAction="http://tempuri.org/ISocratesService/EliminarAlumnoResponse")]
        System.Threading.Tasks.Task EliminarAlumnoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ListarAlumno", ReplyAction="http://tempuri.org/ISocratesService/ListarAlumnoResponse")]
        sistemaasesoriaJAC.SocratesWS.Alumno[] ListarAlumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ListarAlumno", ReplyAction="http://tempuri.org/ISocratesService/ListarAlumnoResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno[]> ListarAlumnoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/CrearDocente", ReplyAction="http://tempuri.org/ISocratesService/CrearDocenteResponse")]
        sistemaasesoriaJAC.SocratesWS.Docente CrearDocente(sistemaasesoriaJAC.SocratesWS.Docente docenteCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/CrearDocente", ReplyAction="http://tempuri.org/ISocratesService/CrearDocenteResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente> CrearDocenteAsync(sistemaasesoriaJAC.SocratesWS.Docente docenteCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ObtenerDocente", ReplyAction="http://tempuri.org/ISocratesService/ObtenerDocenteResponse")]
        sistemaasesoriaJAC.SocratesWS.Docente ObtenerDocente(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ObtenerDocente", ReplyAction="http://tempuri.org/ISocratesService/ObtenerDocenteResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente> ObtenerDocenteAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ModificarDocente", ReplyAction="http://tempuri.org/ISocratesService/ModificarDocenteResponse")]
        sistemaasesoriaJAC.SocratesWS.Docente ModificarDocente(sistemaasesoriaJAC.SocratesWS.Docente docenteModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ModificarDocente", ReplyAction="http://tempuri.org/ISocratesService/ModificarDocenteResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente> ModificarDocenteAsync(sistemaasesoriaJAC.SocratesWS.Docente docenteModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/EliminarDocente", ReplyAction="http://tempuri.org/ISocratesService/EliminarDocenteResponse")]
        void EliminarDocente(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/EliminarDocente", ReplyAction="http://tempuri.org/ISocratesService/EliminarDocenteResponse")]
        System.Threading.Tasks.Task EliminarDocenteAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ListarDocente", ReplyAction="http://tempuri.org/ISocratesService/ListarDocenteResponse")]
        sistemaasesoriaJAC.SocratesWS.Docente[] ListarDocente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocratesService/ListarDocente", ReplyAction="http://tempuri.org/ISocratesService/ListarDocenteResponse")]
        System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente[]> ListarDocenteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocratesServiceChannel : sistemaasesoriaJAC.SocratesWS.ISocratesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocratesServiceClient : System.ServiceModel.ClientBase<sistemaasesoriaJAC.SocratesWS.ISocratesService>, sistemaasesoriaJAC.SocratesWS.ISocratesService {
        
        public SocratesServiceClient() {
        }
        
        public SocratesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocratesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocratesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocratesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public sistemaasesoriaJAC.SocratesWS.Alumno CrearAlumno(sistemaasesoriaJAC.SocratesWS.Alumno alumnoCrear) {
            return base.Channel.CrearAlumno(alumnoCrear);
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno> CrearAlumnoAsync(sistemaasesoriaJAC.SocratesWS.Alumno alumnoCrear) {
            return base.Channel.CrearAlumnoAsync(alumnoCrear);
        }
        
        public sistemaasesoriaJAC.SocratesWS.Alumno ObtenerAlumno(string codigo) {
            return base.Channel.ObtenerAlumno(codigo);
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno> ObtenerAlumnoAsync(string codigo) {
            return base.Channel.ObtenerAlumnoAsync(codigo);
        }
        
        public sistemaasesoriaJAC.SocratesWS.Alumno ModificarAlumno(sistemaasesoriaJAC.SocratesWS.Alumno alumnoModificar) {
            return base.Channel.ModificarAlumno(alumnoModificar);
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno> ModificarAlumnoAsync(sistemaasesoriaJAC.SocratesWS.Alumno alumnoModificar) {
            return base.Channel.ModificarAlumnoAsync(alumnoModificar);
        }
        
        public void EliminarAlumno(string codigo) {
            base.Channel.EliminarAlumno(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarAlumnoAsync(string codigo) {
            return base.Channel.EliminarAlumnoAsync(codigo);
        }
        
        public sistemaasesoriaJAC.SocratesWS.Alumno[] ListarAlumno() {
            return base.Channel.ListarAlumno();
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Alumno[]> ListarAlumnoAsync() {
            return base.Channel.ListarAlumnoAsync();
        }
        
        public sistemaasesoriaJAC.SocratesWS.Docente CrearDocente(sistemaasesoriaJAC.SocratesWS.Docente docenteCrear) {
            return base.Channel.CrearDocente(docenteCrear);
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente> CrearDocenteAsync(sistemaasesoriaJAC.SocratesWS.Docente docenteCrear) {
            return base.Channel.CrearDocenteAsync(docenteCrear);
        }
        
        public sistemaasesoriaJAC.SocratesWS.Docente ObtenerDocente(int codigo) {
            return base.Channel.ObtenerDocente(codigo);
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente> ObtenerDocenteAsync(int codigo) {
            return base.Channel.ObtenerDocenteAsync(codigo);
        }
        
        public sistemaasesoriaJAC.SocratesWS.Docente ModificarDocente(sistemaasesoriaJAC.SocratesWS.Docente docenteModificar) {
            return base.Channel.ModificarDocente(docenteModificar);
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente> ModificarDocenteAsync(sistemaasesoriaJAC.SocratesWS.Docente docenteModificar) {
            return base.Channel.ModificarDocenteAsync(docenteModificar);
        }
        
        public void EliminarDocente(int codigo) {
            base.Channel.EliminarDocente(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarDocenteAsync(int codigo) {
            return base.Channel.EliminarDocenteAsync(codigo);
        }
        
        public sistemaasesoriaJAC.SocratesWS.Docente[] ListarDocente() {
            return base.Channel.ListarDocente();
        }
        
        public System.Threading.Tasks.Task<sistemaasesoriaJAC.SocratesWS.Docente[]> ListarDocenteAsync() {
            return base.Channel.ListarDocenteAsync();
        }
    }
}
