//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platonWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciclo
    {
        public int id { get; set; }
        public string codciclo { get; set; }
        public string desciclo { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string estado { get; set; }
    }
}
