//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platonWSREST.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class platonEntities : DbContext
    {
        public platonEntities()
            : base("name=platonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciclo> ciclo { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<seccion> seccion { get; set; }
    }
}
